### ISSUE TITLE
Feature request: Lint when server starts

### ISSUE THREAD

**Issue by ndabAP** [vmasto/express-babel#6]
It would be cool to have automatically linting when running `npm run dev` instead of actively starting it with `npm run lint`.

**Comment by vmasto** [comment]
Heya, you can achieve that by amending your `dev` script in `package.json` to the folllowing:

`"dev": "nodemon src/index.js --exec \"node -r dotenv/config -r babel-register\" & npm run lint",`

Does that help?

**Comment by ndabAP** [comment]
Hey, that works perfectly, thanks a lot! Why not adding this to `package.json` :) ?

**Comment by vmasto** [comment]
No worries. I'm not adding it because it very much depends on preference, most people want the server output be on a different terminal instance than the lint output, and they also lint inside their editors normally rather than on the terminal. It's a very easy change so I'm leaving it as is for now :) Thanks for your interest btw!

**Comment by ndabAP** [comment]
Just a minimal improvement:

```
"dev": "nodemon src/index.js --exec \"node -r dotenv/config -r babel-register\" | npm run lint"
```

This let's you kill both processes at once with <kbd>Ctrl + C</kbd>.
